version: '3'
# Os containers safepassword e dev não podem subir juntos, pois a porta da api vai conflitar. 
# utilizaremos o Dev apenas para testar o projeto. e o Safepassword para deixar ele rodando no servidor para ser utilizado. 

services:
  SafePassword_Mysql:
    image: mysql
    container_name: SafePassword_Mysql
    hostname: SafePassword_Mysql
    restart: always
    env_file:
      - .env
      - config/database/mysql.env
    ports:
      - 3306:3306
    volumes:
      - "./config/database/init-db/:/docker-entrypoint-initdb.d"
      - "/mnt/c/Volumes_Docker/SafePassword_Mysql:/var/run/mysql"

                                                                                                                                                                                                             

  safepassword:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: safepassword
    # volumes:
    #   - .:/go/src
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - SafePassword_Mysql
  
  dev:
    build: 
      context: ./
      dockerfile : Dockerfile.dev
    container_name: dev
    working_dir: /go/src
    volumes:
      - ./:/go/src
    restart: always
    ports:
      # - ${API_PORT}:${API_PORT}
      - 8001:8001
    depends_on:
      - SafePassword_Mysql

# docker volume create --driver local --opt type=none --opt device=/e/Projetos/go/src/SafePasswordApi/Mysql --opt o=bind vol_mysql_safepassword