INSERT INTO SafePassword.Usuarios (Nome,Email,Senha) values

('Usuario 1', 'usuario1@gmail.com', '$2a$10$s05Q2pymPXvM/KegOjraAOFYHlVJYUL3kSOyPJNXIxHon/2PKDY16'),
('Usuario 2', 'usuario2@gmail.com', '$2a$10$MGk.0Q9Op3DMcuJzoHAcce13r89UROdgNJ281CUkAFw5P2KRQks7W'),
('Usuario 3', 'usuario3@gmail.com', '$2a$10$lkraNpCrLoJ.tWoeFjdjaehLfEQeptyEWYDNJjgrqTX0BPPLnAhhK');

INSERT INTO SafePassword.Senhas ( UsuarioId,Descricao,Login,Senha) values
(1,'Alura','usuario1@gmail.com','Senha1'),
(1,'Udemy','usuario_1','Senha2'),
(1,'Youtube','usuario1_3833@empresa.com','Senha3'),
(2,'Facebook','','Senha1'),
(2,'Spotify','','Senha2');
    ('Usuario 1', 'usuario1@gmail.com', '$2a$10$s05Q2pymPXvM/KegOjraAOFYHlVJYUL3kSOyPJNXIxHon/2PKDY16'),
    ('Usuario 2', 'usuario2@gmail.com', '$2a$10$MGk.0Q9Op3DMcuJzoHAcce13r89UROdgNJ281CUkAFw5P2KRQks7W'),
    ('Usuario 3', 'usuario3@gmail.com', '$2a$10$lkraNpCrLoJ.tWoeFjdjaehLfEQeptyEWYDNJjgrqTX0BPPLnAhhK');

INSERT INTO SafePassword.Senhas ( UsuarioId,Descricao,Login,Senha) values
    (1,'Alura','usuario1@gmail.com','Senha1'),
    (1,'Udemy','usuario_1','Senha2'),
    (1,'Youtube','usuario1_3833@empresa.com','Senha3'),
    (2,'Facebook','','Senha1'),
    (2,'Spotify','','Senha2');

